# Lethe CLI entry point.

import argparse
import asyncio
import sys
import os
import signal
sys.path.append('.')

def cmd_setup():
    print("\n  Lethe Setup\n")
    
    vps_ip = input("  Enter VPS IP address: ").strip()
    vps_domain = input("  Enter VPS domain (e.g. xorgate.duckdns.org): ").strip()
    vps_port = input("  Enter VPS port [443]: ").strip() or "443"
    proxy_host = "127.0.0.1"
    proxy_port = input("  Enter local proxy port [1080]: ").strip() or "1080"
    
    config_content = f"""# Lethe config — generated by setup
VPS_IP = "{vps_ip}"
VPS_PORT = {vps_port}
VPS_DOMAIN = "{vps_domain}"
PROXY_HOST = "{proxy_host}"
PROXY_PORT = {proxy_port}
"""
    
    with open('config.py', 'w') as f:
        f.write(config_content)
    
    print(f"\n   Config saved to config.py")
    print(f"   VPS: {vps_domain} ({vps_ip}:{vps_port})")
    print(f"   Proxy: {proxy_host}:{proxy_port}")
    print(f"\n  Run 'python main.py start' to begin\n")

def cmd_start():
    print("""
    ██╗     ███████╗████████╗██╗  ██╗███████╗
    ██║     ██╔════╝╚══██╔══╝██║  ██║██╔════╝
    ██║     █████╗     ██║   ███████║█████╗  
    ██║     ██╔══╝     ██║   ██╔══██║██╔══╝  
    ███████╗███████╗   ██║   ██║  ██║███████╗
    ╚══════╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚══════╝
    Traffic Obfuscator
    """)
    
    try:
        from config import VPS_IP, VPS_PORT, VPS_DOMAIN, PROXY_HOST, PROXY_PORT
    except ImportError:
        print("   No config found. Run 'python main.py setup' first.\n")
        sys.exit(1)
    
    print(f"  Relay   : {VPS_DOMAIN} ({VPS_IP}:{VPS_PORT})")
    print(f"  Proxy   : {PROXY_HOST}:{PROXY_PORT}")
    print(f"  Cipher  : ChaCha20-Poly1305 + X25519")
    print(f"  Transport: TLS 1.3")
    print(f"\n  Press Ctrl+C to stop\n")
    
    from client.proxy import main
    
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    
    def shutdown():
        print("\n\n  Shutting down Lethe...\n")
        for task in asyncio.all_tasks(loop):
            task.cancel()
        loop.stop()
    
    loop.add_signal_handler(signal.SIGINT, shutdown)
    
    try:
        loop.run_until_complete(main())
    except asyncio.CancelledError:
        pass
    finally:
        loop.close()
        print("   Lethe stopped cleanly\n")

def cmd_status():
    import socket
    
    try:
        from config import PROXY_HOST, PROXY_PORT, VPS_IP, VPS_PORT
    except ImportError:
        print("\n  ✗ No config found. Run 'python main.py setup' first.\n")
        sys.exit(1)
    
    print("\n  Lethe Status\n")
    
    try:
        s = socket.create_connection((PROXY_HOST, PROXY_PORT), timeout=1)
        s.close()
        print(f"   Local proxy running on {PROXY_HOST}:{PROXY_PORT}")
    except:
        print(f"   Local proxy not running on {PROXY_HOST}:{PROXY_PORT}")
    
    try:
        s = socket.create_connection((VPS_IP, VPS_PORT), timeout=3)
        s.close()
        print(f"   VPS reachable at {VPS_IP}:{VPS_PORT}")
    except:
        print(f"   VPS unreachable at {VPS_IP}:{VPS_PORT}")
    
    print()

def main():
    parser = argparse.ArgumentParser(
        prog='lethe',
        description='Lethe — Traffic Obfuscator',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
commands:
  setup     configure VPS and proxy settings
  start     start the local SOCKS5 proxy and tunnel
  status    check if proxy and VPS are reachable
        """
    )
    parser.add_argument('command', choices=['setup', 'start', 'status'])
    
    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit(0)
    
    args = parser.parse_args()
    
    if args.command == 'setup':
        cmd_setup()
    elif args.command == 'start':
        cmd_start()
    elif args.command == 'status':
        cmd_status()

if __name__ == '__main__':
    main()